version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq1
    ports:
      - "5672:5672"   # AMQP port for messaging
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
